### ISSUE TITLE
Specify variables

### ISSUE THREAD

**Issue by Tiffany-Zhu5303** [hunter-classes/spring-2022-135-lab-07-DavidA123777#2]
@DavidA123777 

I think it's good that you leave comments to specify parts of your code. I noticed in your main.cpp file that you have a variable named s.
I would suggest being more specific with naming variables despite things being easier with shorter names.

**Comment by DavidA123777** [comment]
That's a great idea, it makes it harder to read it if I use random letters as variable names.
